server:
  port: 8081

spring:
  application:
    name: catalogue-service

  datasource:
    url: jdbc:postgresql://localhost:5432/projects
    username: postgres
    password: voldemort

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



