server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/projects
    username: postgres
    password: voldemort

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/

  instance:
    prefer-ip-address: true
